name: Get packages (Ubuntu)

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:

  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  get_packages:
    runs-on: ubuntu-latest
    steps:
    - run: echo $(apt list --installed)
